package visual.PanelesAYUDA;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

public class PanelAyuda extends JPanel {

    /**
     * Creates new form panelAyuda
     */
    public PanelAyuda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        LabelFAQ = new javax.swing.JLabel();
        labelPedido = new javax.swing.JLabel();
        LabelPlatillo = new javax.swing.JLabel();
        labelPedidoAutomatico = new javax.swing.JLabel();
        labelPedidoPersonalizado = new javax.swing.JLabel();
        labelExplicacionPedido = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        LabelFAQ.setText("FAQ");

        labelPedido.setText("Pedido");

        LabelPlatillo.setText("Platillo");

        labelPedidoAutomatico.setText("Pedido Automatico");

        labelPedidoPersonalizado.setText("Pedido Personalizado");

        labelExplicacionPedido.setText("explica  en que consiste ");

        jLabel1.setText("explica en que consiste un platillo");

        jLabel2.setText("explica en que consiste un pedido automatico");

        jLabel3.setText("explica en que consiste un pedido personalizado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelFAQ)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPedidoAutomatico)
                            .addComponent(labelPedidoPersonalizado)
                            .addComponent(labelPedido)
                            .addComponent(LabelPlatillo)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelExplicacionPedido)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(LabelFAQ)
                .addGap(24, 24, 24)
                .addComponent(labelPedido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelExplicacionPedido)
                .addGap(24, 24, 24)
                .addComponent(LabelPlatillo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(labelPedidoAutomatico)
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelPedidoPersonalizado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(41, Short.MAX_VALUE))
        );
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    private javax.swing.JLabel LabelFAQ;
    private javax.swing.JLabel LabelPlatillo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelExplicacionPedido;
    private javax.swing.JLabel labelPedido;
    private javax.swing.JLabel labelPedidoAutomatico;
    private javax.swing.JLabel labelPedidoPersonalizado;
    // End of variables declaration                   
}

