package visual.PanelesAYUDA;

public class PanelAyudaMicrofono extends javax.swing.JPanel {
    /** Creates new form jPanelAyudaMicrofono */
    public PanelAyudaMicrofono() {
        initComponents();
    }

    /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        imgExplicacion = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaExplicacion = new javax.swing.JTextArea();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        labelTitulo.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        labelTitulo.setText("Ayuda Microfono");

        imgExplicacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("../assets/MenuBarMicrofono.png"))); // NOI18N
        imgExplicacion.setLabelFor(textAreaExplicacion);
        jScrollPane1.setViewportView(imgExplicacion);

        textAreaExplicacion.setEditable(false);
        textAreaExplicacion.setBackground(new java.awt.Color(240, 240, 240));
        textAreaExplicacion.setColumns(20);
        textAreaExplicacion.setRows(5);
        textAreaExplicacion.setText("El microfono se encuentra en la parte superior, \nen el apartado del menu, con 2 opciones:\n- habilitar: habilita el microfono y funciona entre ventanas\n- deshabilita: terminar de captar las palabras.\nA continuacion se puede observar una imagen explicatoria.\nLas palabras que reconoce son dependiendo de la ventana \ny se muestran sobre la ventana misma.");
        textAreaExplicacion.setBorder(null);
        textAreaExplicacion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(textAreaExplicacion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jScrollPane1))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(96, 96, 96))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                .addGap(8, 8, 8))
        );
    }// </editor-fold>                        

    // Variables declaration - do not modify                     
    private javax.swing.JLabel imgExplicacion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JTextArea textAreaExplicacion;
    // End of variables declaration                   

}