package visual.PanelesFinales;

import javax.swing.*;
import javax.swing.event.*;
import java.awt.event.*;

import java.util.ArrayList;

import clases.Platillo;
import clases.Componente;

public class PanelPlatillo extends JPanel {
    private Platillo platillo;
    private Componente componenteActual;
    /**
     * Creates new form PanelEdicionPedido
     */
    public PanelPlatillo(Platillo p) {
        platillo = p;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        labelTitulo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        labelImagen = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaComponentes = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        CostoLabel = new javax.swing.JTextField();

        labelTitulo.setEditable(false);
        labelTitulo.setText(platillo.getTitulo().toUpperCase());

        //labelImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examples/MenuBarMicrofono.png"))); // NOI18N
        labelImagen.setLabelFor(jPanel2);

        listaComponentes.setModel(new javax.swing.AbstractListModel<PanelComponente>() {
            PanelComponente[] componentes = generarPaneles(platillo);
            public int getSize() { return componentes.length; }
            public PanelComponente getElementAt(int i) { return componentes[i]; }
            private PanelComponente[] generarPaneles(Platillo p) {
                ArrayList<Componente> lista = p.getComponentes();
                PanelComponente[] resp = new PanelComponente[lista.size()];
                for (int i =0 ; i<lista.size(); i++) {
                    resp[i] = new PanelComponente(lista.get(i));
                }
                return resp;
            }
        });
        
        //listaComponentes.setModel(new JList<PanelComponente>());

        listaComponentes.addListSelectionListener(
            new ListSelectionListener() {
                @Override
                public void valueChanged(ListSelectionEvent lse) {
                    if (!lse.getValueIsAdjusting()) {
                        componenteActual = listaComponentes.getSelectedValue()
                            .getComponente();
                        listaComponentes.addKeyListener(new KeyListener() {
                            @Override 
                            public void keyPressed(KeyEvent ke) {
                                int keyCode = ke.getKeyCode();
                                if (keyCode == KeyEvent.VK_UP)
                                    platillo.aumentarComponente(1, componenteActual);
                                else if (keyCode == KeyEvent.VK_DOWN)
                                    // disminuir
                                    platillo.aumentarComponente(-1, componenteActual);
                                recargarPanel();
                            }
                            @Override
                            public void keyReleased(KeyEvent ke) {
                            }
                            @Override
                            public void keyTyped(KeyEvent ke) {
                            }
                        });
                    }

                }
            }
            );
        jScrollPane3.setViewportView(listaComponentes);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(labelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setLabelFor(CostoLabel);
        jLabel1.setText("Costo:");

        CostoLabel.setEditable(false);
        CostoLabel.setText(platillo.getCosto()+"$$");
        CostoLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CostoLabelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(184, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CostoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CostoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>                        

    private void CostoLabelActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                  
    private void recargarPanel() {
        initComponents();
    }


    // Variables declaration - do not modify                     
    private javax.swing.JTextField  CostoLabel;
    private javax.swing.JLabel      jLabel1;
    private javax.swing.JPanel      jPanel2;
    private javax.swing.JPanel      jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel      labelImagen;
    private javax.swing.JTextField  labelTitulo;
    private javax.swing.JList<PanelComponente> listaComponentes;
    // End of variables declaration                   
}